spring.application.name=StarTupHub
spring.datasource.url=jdbc:mysql://localhost:3306/startuphub
spring.datasource.username=root
spring.datasource.password=Jp040711@
spring.jpa.hibernate.dd1-auto=updtae
spring.jpa.show-sql=true
